version: "3"

services:
  db:
    container_name: postgres-article
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: crawler
    restart: always
    ports:
      - 5433:5432 



      